// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAwVC8Kki5DZsx54hjZ2gjhwWy6gQQUVM',
    appId: '1:17721565930:web:5674989aeefb231ac62d93',
    messagingSenderId: '17721565930',
    projectId: 'flash-chat-8cfe2',
    authDomain: 'flash-chat-8cfe2.firebaseapp.com',
    storageBucket: 'flash-chat-8cfe2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpyYw6KcfYW9k3HewU-gj3EgYgRhM_mrw',
    appId: '1:17721565930:android:036e2f01e4c2a3ebc62d93',
    messagingSenderId: '17721565930',
    projectId: 'flash-chat-8cfe2',
    storageBucket: 'flash-chat-8cfe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqZAUjoObWQCf-W2Nx4X7gW9GzU4ugr_U',
    appId: '1:17721565930:ios:238b7c2f95993a3fc62d93',
    messagingSenderId: '17721565930',
    projectId: 'flash-chat-8cfe2',
    storageBucket: 'flash-chat-8cfe2.appspot.com',
    iosBundleId: 'com.example.lightChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqZAUjoObWQCf-W2Nx4X7gW9GzU4ugr_U',
    appId: '1:17721565930:ios:238b7c2f95993a3fc62d93',
    messagingSenderId: '17721565930',
    projectId: 'flash-chat-8cfe2',
    storageBucket: 'flash-chat-8cfe2.appspot.com',
    iosBundleId: 'com.example.lightChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAwVC8Kki5DZsx54hjZ2gjhwWy6gQQUVM',
    appId: '1:17721565930:web:46aed639ea0af64bc62d93',
    messagingSenderId: '17721565930',
    projectId: 'flash-chat-8cfe2',
    authDomain: 'flash-chat-8cfe2.firebaseapp.com',
    storageBucket: 'flash-chat-8cfe2.appspot.com',
  );
}
